-------------------------------------------
<if(buildName)>
<("Nombre Aplicación"); format="style-list-key"> : <buildName; format="style-list-value">
<endif>
<if(buildVersion)>
<("Versión"); format="style-list-key"> : <buildVersion; format="style-list-value">
<endif>
<("Autor"); format="style-list-key"> : <("Eduardo Maravilla"); format="style-list-value">
-------------------------------------------